const { chromium } = require('playwright-core');
const http = require('http'); const fs = require('fs'); const path = require('path');
const ROOT = path.join(__dirname, '..'); const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.json': 'application/json' };
const srv = http.createServer((req, res) => { let p = decodeURIComponent(req.url.split('?')[0]); if (p.endsWith('/')) p += 'index.html'; const f = path.join(ROOT, p); if (!fs.existsSync(f)) { res.writeHead(404); return res.end(); } res.writeHead(200, { 'Content-Type': MIME[path.extname(f)] || 'application/octet-stream' }); res.end(fs.readFileSync(f)); }).listen(8779);
const DB = 'https://script.google.com/macros/s/AKfycbSET/exec';
const t = (n, ok, extra = '') => console.log((ok ? 'PASS' : 'FAIL') + ' ' + n + (extra ? ' — ' + extra : ''));
(async () => {
  const b = await chromium.launch({ ...(process.env.CHROME ? { executablePath: process.env.CHROME } : { channel: 'chrome' }) });
  for (const [name, w, h] of [['phone', 360, 740], ['desktop', 1100, 800]]) {
    const ctx = await b.newContext({ viewport: { width: w, height: h } }); const page = await ctx.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    page.on('dialog', d => d.type() === 'prompt' ? d.accept('GeoSurvey') : d.accept());
    await page.route(u => /nominatim|generativelanguage/.test(u.hostname), r => r.abort());
    await page.route(u => u.hostname === 'script.google.com', r => { const a = new URL(r.request().url()).searchParams.get('action'); r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(a === 'ping' ? { ok: true, version: '1.17.3', sheetUrl: 'https://docs.google.com/spreadsheets/d/SHEET/edit', scriptUrl: 'https://script.google.com/d/SCRIPT/edit', folderUrl: 'y', folderName: 'GeoSurvey Photos', driveError: '', rows: 4, ai: true, aiModel: 'gemma-4-26b-a4b-it' } : { ok: true, rows: [], total: 0, schema: null, ai: true, version: '1.17.3' }) }); });
    await page.addInitScript(() => { try { localStorage.setItem('gs_welcomed', '"x"'); } catch {} });
    await page.goto(`http://localhost:8779/?db=${encodeURIComponent(DB)}`); await page.waitForTimeout(700);
    await page.click('#settingsBtn'); await page.waitForTimeout(300);
    t(`${name}: dialog open`, await page.$eval('#settingsDlg', d => d.open));
    const fit = await page.evaluate(() => { const r = document.getElementById('settingsDlg').getBoundingClientRect(); return r.bottom <= innerHeight + .5 && r.right <= innerWidth + .5 && r.width > 0; });
    t(`${name}: dialog fits the viewport`, fit);
    t(`${name}: Auto selected by default`, await page.$eval('input[name="engine"][value="auto"]', r => r.checked));
    t(`${name}: gemma badge says ready (backend AI on)`, /ready/.test(await page.textContent('.rstat[data-stat="gemma"]')), await page.textContent('.rstat[data-stat="gemma"]'));
    t(`${name}: auto badge points at Gemma 4`, /Gemma 4/.test(await page.textContent('.rstat[data-stat="auto"]')), await page.textContent('.rstat[data-stat="auto"]'));
    await page.click('label.radio:has(input[value="chrome"])'); await page.waitForTimeout(100); t(`${name}: Chrome card reveals the download button`, !(await page.$eval('[data-for="chrome"]', e => e.hidden)) && (await page.$('#chromeDlBtn')) !== null); await page.click('#chromeDlBtn'); await page.waitForTimeout(400); t(`${name}: download button reports status`, (await page.textContent('#chromeDlStatus')).length > 0, await page.textContent('#chromeDlStatus'));
    await page.click('label.radio:has(input[value="gemini"])'); await page.waitForTimeout(100);
    const vis = await page.evaluate(() => [...document.querySelectorAll('[data-for]')].map(e => e.dataset.for + ':' + !e.hidden));
    t(`${name}: only Gemini fields shown for Gemini`, vis.join(',') === 'chrome:false,gemma auto:false,gemini auto:true,openrouter auto:false', vis.join(','));
    await page.fill('#setKey', 'AIzaTEST'); await page.waitForTimeout(100);
    t(`${name}: typing a key flips the badge live`, /key saved/.test(await page.textContent('.rstat[data-stat="gemini"]')));
    await page.click('.pw .eye'); t(`${name}: eye reveals the key`, (await page.$eval('#setTeamKey', i => i.type)) === 'text');
    await page.click('.seg label:has(input[value="1536"])');
    await page.click('#testDbBtn'); await page.waitForTimeout(500);
    t(`${name}: Test (database) shows status inline`, /Backend v1.17.3 OK/.test(await page.textContent('#testDbStatus')), await page.textContent('#testDbStatus'));
    t(`${name}: DB tile turns green after Test`, /Connected · backend v1.17.3/.test(await page.textContent('#stDbText')) && (await page.$eval('#stDb', e => e.classList.contains('ok'))), await page.textContent('#stDbText'));
    t(`${name}: Sheet + Apps Script tiles appear after Test with the right links`, !(await page.$eval('#sheetOpenBtn', a => a.hidden)) && (await page.$eval('#sheetOpenBtn', a => a.href)) === 'https://docs.google.com/spreadsheets/d/SHEET/edit' && (await page.$eval('#scriptOpenBtn', a => a.href)) === 'https://script.google.com/d/SCRIPT/edit');
    t(`${name}: AI tile shows readiness`, /Ready|Not set up/.test(await page.textContent('#stAiText')), await page.textContent('#stAiText'));
    await page.click('#stDb'); await page.waitForTimeout(400); t(`${name}: Database tile runs the test`, /Backend v1.17.3 OK/.test(await page.textContent('#testDbStatus')));
    await page.click('#quickQr'); await page.waitForTimeout(200);
    t(`${name}: quick QR icon opens the QR dialog`, await page.$eval('#qrDlg', d => d.open)); await page.click('#qrClose');
    t(`${name}: quick icons enabled with an endpoint`, !(await page.$eval('#teamLinkBtn', b => b.disabled)) && !(await page.$eval('#quickQr', b => b.disabled)));
    await page.screenshot({ path: `out/settings-${name}.png` });
    await page.click('#saveSettingsBtn'); await page.waitForTimeout(300);
    const s = await page.evaluate(() => JSON.parse(localStorage.getItem('gs_settings')));
    t(`${name}: Save persists engine, key and image size`, s.engine === 'gemini' && s.geminiKey === 'AIzaTEST' && s.maxDim === 1536, JSON.stringify({ e: s.engine, m: s.maxDim }));
    await page.click('#settingsBtn'); await page.waitForTimeout(200);
    t(`${name}: reopen restores radio + segment`, (await page.$eval('input[name="engine"][value="gemini"]', r => r.checked)) && (await page.$eval('input[name="maxdim"][value="1536"]', r => r.checked)));
    await page.click('#closeSettingsX'); t(`${name}: × closes without saving`, !(await page.$eval('#settingsDlg', d => d.open)));
    t(`${name}: no page errors`, !errors.length, errors.join(','));
    await ctx.close();
  }
  await b.close(); srv.close();
})().catch(e => { console.error(e); process.exit(1); });
